name: Upload to COS
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Install coscmd
      run: wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux-amd64 -o /tmp/coscli && chmod a+x /tmp/coscli
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.CosUploadSecretId }}
        SECRET_KEY: ${{ secrets.CosUploadSecretKey }}
        BUCKET: blog-1254083249
        REGION: ap-shanghai
      run: /tmp/coscli config add -a blog -b $BUCKET -r $ap-shanghai -i $SECRET_ID -k $SECRET_KEY --init-skip
    - name: Upload
      run: /tmp/coscli cp -r ${{ github.workspace }}/_site/ cos://blog/ --exclude "./.git/*"
