name: Upload to COS
on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Install coscmd
      run: wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux-amd64 -O /tmp/coscli && chmod a+x /tmp/coscli
    - name: Upload
      env:
        COS_SECRET_ID: ${{ secrets.CosUploadSecretId }}
        COS_SECRET_KEY: ${{ secrets.CosUploadSecretKey }}
      run: /tmp/coscli config add -a blog -b blog-1254083249 -r ap-shanghai --init-skip && /tmp/coscli cp  -i $COS_SECRET_ID -k $COS_SECRET_KEY -r ${{ github.workspace }}/_site/ cos://blog/ --exclude "./.git/*" --fail-output-path ./cos_log || cat ./cos_log/*/*
